name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: 'Set up latest JDK EA from jdk.java.net'
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: EA
      - name: Build
        run: mvn --no-transfer-progress verify
      - name: Upload holy-agent.jar
        uses: actions/upload-artifact@v3
        with:
          name: holy-agent.jar
          path: target/holy-agent.jar